### ISSUE TITLE
Interesting project, would like to ask if we can use it.

### ISSUE THREAD

**Issue by Gumbobrot** [swagkarna/Defeat-Defender-V1.2.0#54]
Hi!

I saw that you have starred our advanced Discord Token Grabber called [Rose-Injector](https://github.com/DamagingRose/Rose-Injector).

We are currently looking for a good script that fully allows to disable or remove Windows Defender, because our current [powershell script](https://github.com/DamagingRose/Rose-Injector/blob/main/components/source/disableDefender.py) is not really good.

For these reasons, I would like to ask for your honest opinion on whether your program could be integrated into our project. If so, I'd like to ask if we can use your scripts.

**Comment by swagkarna** [comment]
ok use it
